import type { Metadata } from 'next'
import { getSession } from '@/utils/auth'
import { SidebarUser } from '@/components/SidebarUser'
import { redirect } from 'next/navigation'
import { Suspense } from 'react'
import Loading from './Loading'


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',

}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const session = await getSession();

    return (

        <div className=' bg-transparent'>
                <span>
                    <SidebarUser session={session} />
                </span>                               
                <Suspense fallback={<Loading/>}>
                <div className="lg:pl-72">
                    <div className="mx-auto max-w-7xl space-y-8 px-2 pt-20 lg:px-8 lg:py-8">
                        <div className="bg-vc-border-gradient rounded-lg p-px shadow-lg shadow-white/20">
                            <div className="rounded-lg shadow-md shadow-gray-300 border bg-white p-3.5 lg:p-6">
                                {children}
                            </div>
                        </div>
                    </div>
                </div>
                </Suspense>
        </div>

    )
}
